# Location of top-level MicroPython directory
MPY_DIR = ../micropython

# Name of module
MOD = sasppu

# Source files (.c or .py)
SRC = sasppu_fast.S

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin)
#ARCH = xtensawin
ARCH = xtensa

CFLAGS += 

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk