# Location of top-level MicroPython directory
MPY_DIR = ../micropython

# Name of module
MOD = sasppu

# Source files (.c or .py)
SRC = sasppu_fast.S sasppu_fast.c

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin)
#ARCH = xtensawin
ARCH = xtensa

CFLAGS += -fPIC
